# Generated by Django 4.1.6 on 2023-03-23 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.AddField(
            model_name='listing',
            name='dateAdded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='zipCode',
            field=models.PositiveIntegerField(default=3000, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('1', 'Seller'), ('0', 'Buyer')], max_length=7),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('targetID', models.CharField(max_length=25)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('senderID', models.ManyToManyField(to='myapp.user')),
            ],
        ),
    ]
