# Generated by Django 4.1.6 on 2023-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_listing_date_listing_dateadded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='messages',
            name='senderID',
        ),
        migrations.AlterField(
            model_name='messages',
            name='targetID',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='messages',
            name='senderID',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
