# Generated by Django 4.1.6 on 2023-04-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('B', 'Buyer'), ('S', 'Seller')], max_length=10),
        ),
    ]
