# Generated by Django 4.1.6 on 2023-02-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('B', 'Buyer'), ('A', 'Admin'), ('S', 'Seller')], max_length=7),
        ),
    ]
