# Generated by Django 4.2 on 2023-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_listing_sellerid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.CharField(blank='', default='text', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='productName',
            field=models.CharField(blank='', default='item', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank='', default='place', max_length=30),
        ),
    ]
