# Generated by Django 4.2 on 2023-04-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
