# Generated by Django 4.2 on 2023-04-17 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sellerID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='myapp.profile'),
        ),
    ]
