# Generated by Django 4.1.6 on 2023-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_listing_title_alter_messages_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='listingID',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='zipCode',
            new_name='productID',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='productName',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='location',
        ),
        migrations.AddField(
            model_name='listing',
            name='sellerID',
            field=models.PositiveIntegerField(null=True, verbose_name=0),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='myapp.listing')),
            ],
        ),
    ]
