# Generated by Django 3.2.12 on 2023-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_listing_sellerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
