# Generated by Django 3.2.12 on 2023-05-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_listing_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
