# Generated by Django 4.2 on 2023-05-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_listing_quantity'),
        ('myapp', '0007_profile_approved'),
    ]

    operations = [
    ]
