# Generated by Django 3.2.12 on 2023-05-04 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_watchlist_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='quantity',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
