# Generated by Django 3.2.12 on 2023-04-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='dateAdded',
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
