# Generated by Django 3.2.12 on 2023-04-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20230411_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='desc',
        ),
    ]
