# Generated by Django 4.2 on 2023-04-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pictureURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='listing',
            field=models.ManyToManyField(to='myapp.listing'),
        ),
    ]
