# Generated by Django 4.2 on 2023-04-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_listing_pictureurl_alter_shoppingcart_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pictureURL',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
