name: DjangoCI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:


    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test_database
          MYSQL_ROOT_PASSWORD: testrootpass
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports: 
          - 3306:3306
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
      
    - name: Run Tests
      run: |
        python manage.py test
