
name: DjangoCI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_database
          MYSQL_ROOT_PASSWORD: testrootpass
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports: ['3306:3306']
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Set up and run tests
      env:
        DB_ENGINE: django.db.backends.mysql
        DB_NAME: portfolio
        DB_USER: root
        DB_PASSWORD: root
      run: |
        sudo systemctl start mysql
        mysql -u$DB_USER -p$DB_PASSWORD -e "CREATE DATABASE $DB_NAME;"
        mysql -u$DB_USER -p$DB_PASSWORD -e "SHOW DATABASES;"
        python3 --version
        python3 -m venv venv
        . venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        cd mysite
        python manage.py makemigrations register
        python manage.py makemigrations vietnam_research gmarker shopping linebot warehouse
        python manage.py migrate
        python manage.py test
   # - name: Grant privileges to test user
   #   run: |
   #     mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%' IDENTIFIED BY 'test_pass';"
   #     mysql -u root -e "FLUSH PRIVILEGES;"
        
   # - name: Run Migrations
   #   run: python manage.py migrate
        
   # - name: Start MySQL service
   #   run: |
   #    sudo systemctl start mysql
        
   # - name: Run tests
    #  env:
     #   DATABASE_URL: mysql://${{ env.MYSQL_USER }}:${{ env.MYSQL_PASSWORD }}@localhost/${{ env.MYSQL_DATABASE }}
      #run: |
       # python manage.py test
