name: DjangoCI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0.32
        env:
          MYSQL_DATABASE: test_database
          MYSQL_ROOT_PASSWORD: testrootpass
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
        ports: ['3306:3306']
        
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    

    - name: Grant privileges to test user
      run: |
        mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test_user'@'%' IDENTIFIED BY 'test_pass';"
        mysql -u root -e "FLUSH PRIVILEGES;"
        
    - name: Run tests
      env:
        DATABASE_URL: mysql://${{ env.MYSQL_USER }}:${{ env.MYSQL_PASSWORD }}@localhost/${{ env.MYSQL_DATABASE }}
      run: |
        python manage.py test
